- name: Ensure the nginx container is running
  hosts: all
  become: yes
  tasks:
  - name: Start nginx container and ensure it's always running
    community.docker.docker_container:
      name: nginx_container
      image: nginx:latest
      state: started
      restart_policy: always
      ports:
      - "80:80"
